name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.83.1'

    - name: Build
      run: hugo --minify

    - name: Upload to artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./public
